import type { Datasheet } from '../../core/types';

export const BattleSistersSquad: Datasheet = {
  id: '',
  stats: [
    {
      name: 'Battle Sisters Squad',
      movement: 6,
      toughness: 3,
      save: 3,
      invuln: 6,
      wounds: 1,
      leadership: 7,
      objective: 2,
    },
  ],
  enhancements: [],
  rangedWeapons: {
    ArtificerCraftedStormBolter: {
      type: 'ranged',
      quantity: 0,
      name: 'Artificer-crafted storm bolter',
      subtitle: '',
      keywords: ['Rapid Fire 2'],
      range: 24,
      attacks: 2,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 2,
    },
    BoltPistol: {
      type: 'ranged',
      quantity: 0,
      name: 'Bolt pistol',
      subtitle: '',
      keywords: ['Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    Boltgun: {
      type: 'ranged',
      quantity: 0,
      name: 'Boltgun',
      subtitle: '',
      keywords: ['Rapid Fire 1'],
      range: 24,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    CombiWeapon: {
      type: 'ranged',
      quantity: 0,
      name: 'Combi-weapon',
      subtitle: '',
      keywords: ['Anti-Infantry 4+', 'Devastating Wounds', 'Rapid Fire 1'],
      range: 24,
      attacks: 1,
      ballisticSkill: 4,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    CondemnorBoltgun: {
      type: 'ranged',
      quantity: 0,
      name: 'Condemnor boltgun',
      subtitle: '',
      keywords: [
        'Anti-Psyker 2+',
        'Devastating Wounds',
        'Precision',
        'Rapid Fire 1',
      ],
      range: 24,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    HeavyBolter: {
      type: 'ranged',
      quantity: 0,
      name: 'Heavy Bolter',
      subtitle: '',
      keywords: ['Heavy', 'Sustained Hits 1'],
      range: 24,
      attacks: 3,
      ballisticSkill: 4,
      strength: 5,
      armorPen: 1,
      damage: 2,
    },
    InfernoPistol: {
      type: 'ranged',
      quantity: 0,
      name: 'Inferno pistol',
      subtitle: '',
      keywords: ['Melta 2', 'Pistol'],
      range: 6,
      attacks: 1,
      ballisticSkill: 3,
      strength: 8,
      armorPen: 4,
      damage: 'D3',
    },
    Meltagun: {
      type: 'ranged',
      quantity: 0,
      name: 'Meltagun',
      subtitle: '',
      keywords: ['Melta 2'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 9,
      armorPen: 4,
      damage: 'D6',
    },
    MinistorumFlamer: {
      type: 'ranged',
      quantity: 0,
      name: 'Ministorum flamer',
      subtitle: '',
      keywords: ['Ignores Cover', 'Torrent'],
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 5,
      armorPen: 0,
      damage: 1,
    },
    MinistorumHandFlamer: {
      type: 'ranged',
      quantity: 0,
      name: 'Ministorum hand flamer',
      subtitle: '',
      keywords: ['Ignores Cover', 'Pistol', 'Torrent'],
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    MinistorumHeavyFlamer: {
      type: 'ranged',
      quantity: 0,
      name: 'Ministorum heavy flamer',
      subtitle: '',
      keywords: ['Ignores Cover', 'Torrent'],
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 6,
      armorPen: 1,
      damage: 1,
    },
    MultiMelta: {
      type: 'ranged',
      quantity: 0,
      name: 'Multi-melta',
      subtitle: '',
      keywords: ['Heavy', 'Melta 2'],
      range: 18,
      attacks: 2,
      ballisticSkill: 4,
      strength: 9,
      armorPen: 4,
      damage: 'D6',
    },
    PlasmaPistolStandard: {
      type: 'ranged',
      quantity: 0,
      profiled: true,
      name: 'Plasma pistol',
      subtitle: 'Standard',
      keywords: ['Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 7,
      armorPen: 2,
      damage: 1,
    },
    PlasmaPistolSupercharge: {
      type: 'ranged',
      quantity: 0,
      profiled: true,
      name: 'Plasma pistol',
      subtitle: 'Supercharge',
      keywords: ['Hazardous', 'Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 8,
      armorPen: 3,
      damage: 2,
    },
  },
  meleeWeapons: {
    Chainsword: {
      type: 'melee',
      quantity: 0,
      name: 'Chainsword',
      subtitle: '',
      keywords: [],
      range: 'Melee',
      attacks: 3,
      weaponSkill: 4,
      strength: 3,
      armorPen: 0,
      damage: 1,
    },
    CloseCombatWeapon: {
      type: 'melee',
      quantity: 0,
      name: 'Close combat weapon',
      subtitle: '',
      keywords: [],
      range: 'Melee',
      attacks: 1,
      weaponSkill: 4,
      strength: 3,
      armorPen: 0,
      damage: 1,
    },
    PowerWeapon: {
      type: 'melee',
      quantity: 0,
      name: 'Power weapon',
      subtitle: '',
      keywords: [],
      range: 'Melee',
      attacks: 2,
      weaponSkill: 4,
      strength: 4,
      armorPen: 2,
      damage: 1,
    },
  },
  abilities: {
    core: [],
    faction: 'Acts of Faith',
    datasheetAbilities: [
      {
        name: 'Cherub',
        effect:
          'Once per battle, after this unit has performed an Act of Faith, you gain 1 Miracle dice.',
        note: "Designer's Note: Place a Cherub token next to the unit, removing it once this ability has been used.",
      },
      {
        name: 'Defenders of the Faith',
        effect:
          'At the end of your Command phase, if this unit is within range of an objective marker you control, that object marker remains under your control, even if you have no models within range of it, until your opponent controls it at the start or end of any turn.',
      },
    ],
  },
  wargearAbilities: [
    {
      equipped: false,
      name: 'Simulacrum Imperialis',
      effect:
        'At the end of your Command phase, for each objective marker you control that has one or more units from your army with this ability within range of it, roll one D6: on a 4+, you gain 1 Miracle dice showing a value equal to that result.',
    },
  ],
  setupAbilities: [],
  wargearOptions: [
    {
      entry:
        "The Sister Superior's boltgun can be replaced with one of the following:",
      options: [
        '1 bolt pistol',
        '1 combi-weapon',
        '1 condemnor boltgun',
        '1 inferno pistol',
        '1 Ministorum hand flamer',
        '1 plasma pistol',
      ],
    },
    {
      entry: 'The Sister Superior can be equipped with one of the following:',
      options: ['1 chainsword', '1 power weapon'],
    },
    {
      entry:
        "1 Battle Sister's boltgun can be replaced with one of the following:",
      options: [
        '1 artificer-crafted storm bolter',
        '1 meltagun',
        '1 Ministorum flamer',
      ],
    },
    {
      entry:
        "1 Battle Sister\'s boltgun can be replaced with one of the following:",
      options: [
        '1 artificer-crafted storm bolter',
        '1 heavy bolter',
        '1 meltagun',
        '1 Ministorum flamer',
        '1 Ministorum heavy flamer',
        '1 multi-melta',
      ],
    },
    {
      entry:
        "1 Battle Sister equipped with 1 boltgun can be equipped with 1 simulacrum imperialis (that model\'s boltgun cannot be replaced).",
    },
  ],
  unitComposition: {
    models: ['1 Sister Superior', '9 Battle Sisters'],
    defaultWeapons: [
      'Every Battle Sister is equipped with: bolt pistol; boltgun; close combat weapon.',
    ],
    points: [
      {
        quantity: '10 models',
        total: 105,
      },
    ],
    baseSizes: [
      {
        model: 'Battle Sister Squad',
        size: 32,
      },
    ],
  },
  keywords: [
    'Infantry',
    'Grenades',
    'Battleline',
    'Imperium',
    'Battle Sisters Squad',
  ],
  leaderAbility: [],
  factionKeywords: ['Adepta Sororitas'],
};
