import type { Datasheet } from '../../core/types';

export const Castigator: Datasheet = {
  id: '',
  stats: [
    {
      name: 'Castigator',
      movement: 10,
      toughness: 10,
      save: 3,
      invuln: 6,
      wounds: 11,
      leadership: 7,
      objective: 3,
    },
  ],
  enhancements: [],
  rangedWeapons: {
    CastigatorAutocannons: {
      model: 'Castigator',
      armorPen: 1,
      attacks: 4,
      ballisticSkill: 3,
      damage: 3,
      keywords: ['Twin-linked', 'Rapid Fire 4'],
      name: 'Castigator autocannons',
      quantity: 0,
      range: 48,
      strength: 9,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    CastigatorBattleCannon: {
      model: 'Castigator',
      armorPen: 1,
      attacks: 'D6+3',
      ballisticSkill: 3,
      damage: 3,
      keywords: ['Blast', 'Ignores Cover'],
      name: 'Castigator battle cannon',
      quantity: 0,
      range: 48,
      strength: 10,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    HeavyBolter: {
      model: 'Castigator',
      armorPen: 1,
      attacks: 3,
      ballisticSkill: 3,
      damage: 2,
      keywords: ['Sustained Hits 1'],
      name: 'Heavy bolter',
      quantity: 0,
      range: 36,
      strength: 5,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    HunterKillerMissile: {
      model: 'Castigator',
      armorPen: 3,
      attacks: 1,
      ballisticSkill: 2,
      damage: 'D6',
      keywords: ['One Shot'],
      name: 'Hunter-killer missile',
      quantity: 0,
      range: 48,
      strength: 14,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    StormBolter: {
      model: 'Castigator',
      armorPen: 0,
      attacks: 2,
      ballisticSkill: 3,
      damage: 1,
      keywords: ['Rapid Fire 2'],
      name: 'Storm bolter',
      quantity: 0,
      range: 24,
      strength: 4,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
  },
  meleeWeapons: {
    ArmouredTracks: {
      model: 'Castigator',
      armorPen: 0,
      attacks: 3,
      damage: 1,
      keywords: [],
      name: 'Armoured tracks',
      quantity: 0,
      range: 'Melee',
      strength: 6,
      subtitle: '',
      type: 'melee',
      weaponSkill: 4,
      profiled: false,
    },
  },
  abilities: {
    core: ['Deadly Demise D3'],
    faction: 'Acts of Faith',
    datasheetAbilities: [
      {
        name: 'Rites of Castigation',
        effect:
          'In your Shooting phase, after this model has shot, select one enemy unit hit by one or more of those attacks. Until the end of the turn, each time a friendly Adepta Sororitas unit makes a ranged attack that targets that enemy unit, improve the Armour Penetration characteristic of that attack by 1. The same enemy unit can only be affected by this ability once per turn.',
      },
    ],
  },
  damaged: {
    title: '1-4 Wounds Remaining',
    text: 'While this model has 1-4 wounds remaining, each time this model makes an attack, subtract 1 from the Hit roll.',
  },
  wargearAbilities: {},
  leaderAbility: [],
  wargearOptions: [
    {
      entry:
        "This model's Castigator autocannons can be replaced with 1 Castigator battle cannon.",
    },
    {
      entry: 'This Castigator can be equipped with 1 hunter-killer missile.',
    },
    {
      entry: 'This Castigator can be equipped with 1 storm bolter.',
    },
  ],
  unitComposition: {
    models: ['1 Castigator'],
    defaultWeapons: [
      'This Castigator is equipped with: Castigator autocannons; 3 heavy bolters; armoured tracks.',
    ],
    points: [
      {
        quantity: '1 Castigator',
        total: 160,
      },
    ],
    baseSizes: [
      {
        model: 'Castigator',
        size: 'Hull',
      },
    ],
  },
  keywords: ['Vehicle', 'Smoke', 'Imperium', 'Castigator'],
  factionKeywords: ['Adepta Sororitas'],
  setupAbilities: [],
};
