import type { Datasheet } from '../../core/types';

export const CelestianSacresants: Datasheet = {
  id: '',
  stats: [
    {
      name: 'Celestian Sacresants',
      movement: 6,
      toughness: 3,
      save: 3,
      invuln: 4,
      wounds: 1,
      leadership: 7,
      objective: 1,
    },
  ],
  enhancements: [],
  rangedWeapons: [
    {
      armorPen: 1,
      attacks: 1,
      ballisticSkill: 3,
      damage: 1,
      keywords: ['Pistol'],
      name: 'Bolt pistol',
      quantity: 0,
      range: 12,
      strength: 4,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    {
      armorPen: 4,
      attacks: 1,
      ballisticSkill: 3,
      damage: 'D3',
      keywords: ['Pistol', 'Melta 2'],
      name: 'Inferno pistol',
      quantity: 0,
      range: 6,
      strength: 8,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    {
      armorPen: 0,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      damage: 1,
      keywords: ['Ignores Cover', 'Pistol', 'Torrent'],
      name: 'Ministorum hand flamer',
      quantity: 0,
      range: 12,
      strength: 4,
      subtitle: '',
      type: 'ranged',
      profiled: false,
    },
    {
      armorPen: 2,
      attacks: 1,
      ballisticSkill: 3,
      damage: 1,
      keywords: ['Pistol'],
      name: 'Plasma pistol',
      quantity: 0,
      range: 12,
      strength: 7,
      subtitle: 'standard',
      type: 'ranged',
      profiled: true,
    },
    {
      armorPen: 3,
      attacks: 1,
      ballisticSkill: 3,
      damage: 2,
      keywords: ['Hazardous', 'Pistol'],
      name: 'Plasma pistol',
      quantity: 0,
      range: 12,
      strength: 8,
      subtitle: 'supercharge',
      type: 'ranged',
      profiled: true,
    },
  ],
  meleeWeapons: [
    {
      armorPen: 2,
      attacks: 3,
      weaponSkill: 3,
      damage: 1,
      keywords: ['Sustained Hits 1'],
      name: 'Anointed Halberd',
      quantity: 0,
      range: 'Melee',
      strength: 5,
      subtitle: '',
      type: 'melee',
      profiled: false,
    },
    {
      armorPen: 1,
      attacks: 3,
      weaponSkill: 3,
      damage: 2,
      keywords: ['Lethal Hits'],
      name: 'Hallowed Mace',
      quantity: 0,
      range: 'Melee',
      strength: 4,
      subtitle: '',
      type: 'melee',
      profiled: false,
    },
    {
      armorPen: 2,
      attacks: 3,
      weaponSkill: 3,
      damage: 2,
      keywords: ['Lethal Hits'],
      name: 'Spear of the faithful',
      quantity: 0,
      range: 'Melee',
      strength: 5,
      subtitle: '',
      type: 'melee',
      profiled: false,
    },
  ],
  abilities: {
    core: [],
    faction: 'Acts of Faith',
    datasheetAbilities: [
      {
        name: 'Sworn Protectors',
        effect:
          'While an Adepta Sororitas Character is leading this unit, each time an attack targets this unit, subtract 1 from the Wound roll.',
      },
    ],
  },
  wargearAbilities: [],
  leaderAbility: [],
  wargearOptions: [
    {
      entry:
        "The Sacresants Superior's hallowed mace can be replaced with 1 spear of the faithful.",
    },
    {
      entry:
        "The Sacresants Superior's bolt pistol can be replaced with one of the following:",
      options: [
        '1 inferno pistol',
        '1 Ministorum hand flamer',
        '1 plasma pistol',
      ],
    },
    {
      entry:
        'Any number of Sacresants can each have their hallowed mace replaced with 1 anointed halberd.',
    },
  ],
  unitComposition: {
    models: ['1 Sacresant Superior', '4-9 Celestian Sacresants'],
    defaultWeapons: [
      'Each Sacresant is equipped with: bolt pistol; hallowed mace',
    ],
    points: [
      {
        quantity: '5 Sacresants',
        total: 70,
      },
      {
        quantity: '10 Sacresants',
        total: 130,
      },
    ],
    baseSizes: [
      {
        model: 'Sacresants',
        size: 32,
      },
    ],
  },
  keywords: ['Infantry', 'Grenades', 'Imperium', 'Celestian Sacresants'],
  factionKeywords: ['Adepta Sororitas'],
  setupAbilities: [],
};
