import type { DatasheetProps } from '../../../components/Datasheet';

export const DominionSquad: DatasheetProps = {
  name: 'Dominion Squad',
  movement: 6,
  toughness: 3,
  save: 3,
  invuln: 6,
  wounds: 1,
  leadership: 7,
  objective: 1,
  rangedWeapons: [
    {
      type: 'ranged',
      quantity: 0,
      name: 'Artificer-crafted storm bolter',
      keywords: ['Rapid Fire 2', 'Assault'],
      range: 24,
      attacks: 2,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 2,
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Bolt pistol',
      keywords: ['Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Boltgun',
      keywords: ['Assault', 'Rapid Fire 1'],
      range: 24,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Combi-weapon',
      keywords: ['Anti-Infantry 4+', 'Devastating Wounds', 'Rapid Fire 1'],
      range: 24,
      attacks: 1,
      ballisticSkill: 4,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Condemnor boltgun',
      keywords: [
        'Anti-Psyker 2+',
        'Devastating Wounds',
        'Precision',
        'Rapid Fire 1',
      ],
      range: 24,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Inferno pistol',
      keywords: ['Melta 2', 'Pistol'],
      range: 6,
      attacks: 1,
      ballisticSkill: 3,
      strength: 8,
      armorPen: 4,
      damage: 'D3',
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Meltagun',
      keywords: ['Assault', 'Melta 2'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 9,
      armorPen: 4,
      damage: 'D6',
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Ministorum flamer',
      keywords: ['Assault', 'Ignores Cover', 'Torrent'],
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 5,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      name: 'Ministorum hand flamer',
      keywords: ['Ignores Cover', 'Pistol', 'Torrent'],
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      profiled: true,
      name: 'Plasma pistol - standard',
      keywords: ['Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 7,
      armorPen: 2,
      damage: 1,
    },
    {
      type: 'ranged',
      quantity: 0,
      profiled: true,
      name: 'Plasma pistol - supercharge',
      keywords: ['Hazardous', 'Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 8,
      armorPen: 3,
      damage: 2,
    },
  ],
  meleeWeapons: [
    {
      type: 'melee',
      quantity: 0,
      name: 'Chainsword',
      keywords: [],
      range: 'Melee',
      attacks: 3,
      weaponSkill: 4,
      strength: 3,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'melee',
      quantity: 0,
      name: 'Close combat weapon',
      keywords: [],
      range: 'Melee',
      attacks: 1,
      weaponSkill: 4,
      strength: 3,
      armorPen: 0,
      damage: 1,
    },
    {
      type: 'melee',
      quantity: 0,
      name: 'Power weapon',
      keywords: [],
      range: 'Melee',
      attacks: 2,
      weaponSkill: 4,
      strength: 4,
      armorPen: 2,
      damage: 1,
    },
  ],
  abilities: {
    core: ['Scouts 6"'],
    faction: 'Acts of Faith',
    datasheetAbilities: [
      {
        name: 'Cherub',
        effect:
          'Once per battle, after this unit has performed an Act of Faith, you gain 1 Miracle dice.',
        note: "Designer's Note: Place a Cherub token next to the unit, removing it once this ability has been used.",
      },
      {
        name: 'Righteous Awareness',
        effect:
          'Once per turn, when an enemy unit ends a Normal, Advance, or Fall Back move within 9" of this unit, if this unit is not within Engagement Range of one or more enemy units, it can make a Normal move of up to D6"',
      },
    ],
  },
  wargearAbilities: [
    {
      name: 'Simulacrum Imperialis',
      effect:
        'At the end of your Command phase, for each objective marker you control that has one or more units from your army with this ability within range of it, roll one D6: on a 4+, you gain 1 Miracle dice showing a value equal to that result.',
    },
  ],
  setupAbilities: [
    {
      name: 'Holy Vanguard',
      effect:
        'If this unit has a Leader unit attached to it during the Declare Battle Formations step and this unit starts the battle embarked within a TRANSPORT, that Leader unit gains the Scouts 6" ability.',
    },
  ],
  wargearOptions: [
    {
      entry:
        "The Dominion Superior's boltgun can be replaced with one of the following:",
      options: [
        '1 bolt pistol',
        '1 combi-weapon',
        '1 condemnor boltgun',
        '1 inferno pistol',
        '1 Ministorum hand flamer',
        '1 plasma pistol',
      ],
    },
    {
      entry: 'The Dominion Superior can be equipped with one of the following:',
      options: ['1 chainsword', '1 power weapon'],
    },
    {
      entry:
        'Up to 4 Dominions can each have their boltgun replaced with one of the following:',
      options: [
        '1 artificer-crafted storm bolter',
        '1 meltagun',
        '1 Ministorum flamer',
      ],
    },
    {
      entry:
        "1 Dominion equipped with 1 boltgun can be equipped with 1 simulacrum imperialis (that model's boltgun cannot be replaced).",
    },
  ],
  unitComposition: {
    models: ['1 Dominion Superior', '9 Dominions'],
    defaultWeapons: [
      'Every model is equipped with: bolt pistol; boltgun; close combat weapon.',
    ],
    points: [
      {
        quantity: '10 models',
        total: 115,
      },
    ],
    baseSize: 32,
  },
  keywords: ['Infantry', 'Grenades', 'Imperium', 'Dominion Squad'],
  factionKeywords: ['Adepta Sororitas'],
};
