import type { Datasheet } from '../../core/types';

export const ParagonWarsuits: Datasheet = {
  id: '',
  stats: [
    {
      name: 'Paragon Warsuits',
      movement: 8,
      toughness: 7,
      save: 2,
      invuln: 4,
      wounds: 4,
      leadership: 7,
      objective: 2,
    },
  ],
  enhancements: {},
  rangedWeapons: {
    BoltPistol: {
      model: 'Paragon Warsuits',
      type: 'ranged',
      quantity: 0,
      name: 'Bolt pistol',
      subtitle: '',
      keywords: ['Pistol'],
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
    HeavyBolter: {
      model: 'Paragon Warsuits',
      type: 'ranged',
      quantity: 0,
      name: 'Heavy Bolter',
      subtitle: '',
      keywords: ['Sustained Hits 1'],
      range: 36,
      attacks: 3,
      ballisticSkill: 3,
      strength: 5,
      armorPen: 1,
      damage: 2,
    },
    MinistorumHeavyFlamer: {
      model: 'Paragon Warsuits',
      type: 'ranged',
      quantity: 0,
      name: 'Ministorum heavy flamer',
      subtitle: '',
      keywords: ['Ignores Cover', 'Torrent'],
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 6,
      armorPen: 1,
      damage: 1,
    },
    MultiMelta: {
      model: 'Paragon Warsuits',
      type: 'ranged',
      quantity: 0,
      name: 'Multi-melta',
      subtitle: '',
      keywords: ['Melta 2'],
      range: 18,
      attacks: 2,
      ballisticSkill: 3,
      strength: 9,
      armorPen: 4,
      damage: 'D6',
    },
    ParagonGrenadeLaunchers: {
      model: 'Paragon Warsuits',
      type: 'ranged',
      quantity: 0,
      name: 'Paragon grenade launchers',
      subtitle: '',
      keywords: ['Twin-linked'],
      range: 24,
      attacks: 1,
      ballisticSkill: 3,
      strength: 9,
      armorPen: 2,
      damage: 'D3',
    },
    ParagonStormBolters: {
      model: 'Paragon Warsuits',
      type: 'ranged',
      quantity: 0,
      name: 'Paragon storm bolters',
      subtitle: '',
      keywords: ['Rapid Fire 2', 'Twin-linked'],
      range: 24,
      attacks: 2,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
    },
  },
  meleeWeapons: {
    ParagonWarBlade: {
      model: 'Paragon Warsuits',
      type: 'melee',
      quantity: 0,
      name: 'Paragon war blade',
      subtitle: '',
      keywords: [],
      range: 'Melee',
      attacks: 4,
      weaponSkill: 3,
      strength: 8,
      armorPen: 2,
      damage: 2,
    },
    ParagonWarMace: {
      model: 'Paragon Warsuits',
      type: 'melee',
      quantity: 0,
      name: 'Paragon war mace',
      subtitle: '',
      keywords: [],
      range: 'Melee',
      attacks: 3,
      weaponSkill: 3,
      strength: 12,
      armorPen: 1,
      damage: 3,
    },
  },
  abilities: {
    core: [],
    faction: 'Acts of Faith',
    datasheetAbilities: [
      {
        name: 'Righteous Paragons',
        effect:
          'Each time a model in this unit makes an attack that targets a MONSTER or VEHICLE unit, add 1 to the Hit roll and add 1 to the Wound roll.',
      },
    ],
  },
  wargearAbilities: {},
  leaderAbility: [],
  wargearOptions: [
    {
      entry:
        'Any number of Paragon Warsuits can each have their Paragon storm bolters replaced with 1 Paragon grenade launchers.',
    },
    {
      entry:
        'Any number of Paragon Warsuits can each have their heavy bolter replaced with one of the following:',
      options: ['1 Ministorum heavy flamer', '1 multi-melta'],
    },
    {
      entry:
        'Any number of Paragon Warsuits can each have their Paragon war blade replaced with 1 Paragon war mace.',
    },
  ],
  unitComposition: {
    models: ['1 Paragon Superior', '2 Paragons'],
    defaultWeapons: [
      'Paragon Warsuits are equipped with: bolt pistol; heavy bolter; Paragon storm bolters; Paragon war blade.',
    ],
    points: [
      {
        quantity: '3 Paragon Warsuits',
        total: 210,
      },
    ],
    baseSizes: [
      {
        model: 'Paragon Warsuits',
        size: 50,
      },
    ],
  },
  keywords: ['Vehicle', 'Walker', 'Grenades', 'Imperium', 'Paragon Warsuits'],
  factionKeywords: ['Adepta Sororitas'],
  setupAbilities: [],
};
