import type { Datasheet } from '../../core/types';

export const SeraphimSquad: Datasheet = {
  id: '',
  stats: [
    {
      name: 'Seraphim Squad',
      movement: 12,
      toughness: 3,
      save: 3,
      invuln: 5,
      wounds: 1,
      leadership: 7,
      objective: 1,
    },
  ],
  enhancements: [],
  rangedWeapons: {
    BoltPistol: {
      quantity: 0,
      type: 'ranged',
      profiled: false,
      name: 'Bolt pistol',
      subtitle: '',
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 4,
      armorPen: 0,
      damage: 1,
      keywords: ['Pistol'],
    },
    InfernoPistol: {
      quantity: 0,
      type: 'ranged',
      profiled: false,
      name: 'Inferno pistol',
      subtitle: '',
      range: 6,
      attacks: 1,
      ballisticSkill: 3,
      strength: 8,
      armorPen: 4,
      damage: 'D3',
      keywords: ['Melta 2', 'Pistol'],
    },
    MinistorumHandFlamer: {
      quantity: 0,
      type: 'ranged',
      profiled: false,
      name: 'Ministorum hand flamer',
      subtitle: '',
      range: 12,
      attacks: 'D6',
      ballisticSkill: 'N/A',
      strength: 4,
      armorPen: 0,
      damage: 1,
      keywords: ['Ignores Cover', 'Pistol', 'Torrent'],
    },
    PlasmaPistolStandard: {
      quantity: 0,
      type: 'ranged',
      profiled: true,
      name: 'Plasma pistol',
      subtitle: 'standard',
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 7,
      armorPen: 2,
      damage: 1,
      keywords: ['Pistol'],
    },
    PlasmaPistolSupercharge: {
      quantity: 0,
      type: 'ranged',
      profiled: true,
      name: 'Plasma pistol',
      subtitle: 'supercharge',
      range: 12,
      attacks: 1,
      ballisticSkill: 3,
      strength: 8,
      armorPen: 3,
      damage: 2,
      keywords: ['Hazardous', 'Pistol'],
    },
  },
  meleeWeapons: {
    Chainsword: {
      quantity: 0,
      type: 'melee',
      profiled: false,
      name: 'Chainsword',
      subtitle: '',
      range: 'Melee',
      attacks: 4,
      weaponSkill: 3,
      strength: 3,
      armorPen: 0,
      damage: 1,
      keywords: [],
    },
    CloseCombatWeapon: {
      quantity: 0,
      type: 'melee',
      profiled: false,
      name: 'Close combat weapon',
      subtitle: '',
      range: 'Melee',
      attacks: 2,
      weaponSkill: 3,
      strength: 3,
      armorPen: 0,
      damage: 1,
      keywords: [],
    },
    PowerWeapon: {
      quantity: 0,
      type: 'melee',
      profiled: false,
      name: 'Power weapon',
      subtitle: '',
      range: 'Melee',
      attacks: 3,
      weaponSkill: 3,
      strength: 4,
      armorPen: 2,
      damage: 1,
      keywords: [],
    },
  },
  abilities: {
    core: ['Deep Strike'],
    faction: 'Acts of Faith',
    datasheetAbilities: [
      {
        name: 'Angelic Ascent',
        effect:
          'In your Shooting phase, after this unit has shot, if it is not within Engagement Range of any enemy units, it can make a Normal move of up to 6". If it does, until the end of the turn, this unit is not elligible to declare a charge.',
      },
    ],
  },
  wargearAbilities: [],
  leaderAbility: [],
  wargearOptions: [
    {
      entry:
        "The Seraphim Superior's 2 bolt pistols can be replaced with one of the following:",
      options: [
        '1 bolt pistol and 1 chainsword',
        '1 bolt pistol and 1 plasma pistol',
        '1 bolt pistol and 1 power weapon',
        '1 plasma pistol and 1 chainsword',
        '1 plasma pistol and 1 power weapon',
      ],
    },
    {
      entry:
        'For every 5 models in the unit, up to 2 Seraphim can each have their 2 bolt pistols replaced with one of the following:',
      options: ['2 inferno pistol', '2 Ministorum hand flamers'],
    },
  ],
  unitComposition: {
    models: ['1 Seraphim Superior', '4-9 Seraphim'],
    defaultWeapons: [
      'Each Seraphim is equipped with: 2 bolt pistols; close combat weapon',
    ],
    points: [
      {
        quantity: '5 Seraphim',
        total: 80,
      },
      {
        quantity: '10 Seraphim',
        total: 160,
      },
    ],
    baseSizes: [
      {
        model: 'Seraphim',
        size: 32,
      },
    ],
  },
  keywords: [
    'Infantry',
    'Jump Pack',
    'Fly',
    'Grenades',
    'Imperium',
    'Seraphim Squad',
  ],
  factionKeywords: ['Adepta Sororitas'],
  setupAbilities: [],
};
